---
title: Uterörelsen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hej@uterorelsen.se
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: https://uterorelsen.se
twitter_username: 
github_username: 
theme: minima
plugins:
- jekyll-feed
