---
title: Uterörelsen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hej@uterorelsen.se
description: Genom Uterörelsen inspirerar Johan Forngren till lek, dans och rörelseglädje
  utomhus hos stora och små i Örebro med omnejd.
baseurl: 
url: https://uterorelsen.se
twitter_username: 
github_username: 
theme: minima
plugins:
- jekyll-feed
